### ISSUE TITLE
9.2 - poprawki

### ISSUE THREAD

**Issue by michal-bootcamp** [WieMon/project-pizzeria#1]
1. [scss] masz podwójnie zagnieżdżony folder `partials` przez co przy budowaniu projektu terminal rzuca błędem
2. [js] stosując notację "nawiasową" nie używaj spacji przed nawiasem np. tutaj `thisProduct.data.params [paramId]`
więcej info: https://medium.com/dailyjs/dot-notation-vs-bracket-notation-eedea5fa8572

**Comment by WieMon** [comment]
Poprawione
